In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [50]:
data_path = '../data/'
photos = pd.read_csv(data_path + 'photos.csv')
comments = pd.read_csv(data_path + 'comments.csv')
likes = pd.read_csv(data_path + 'likes.csv')
follows = pd.read_csv(data_path + 'follows.csv')
photo_tags = pd.read_csv(data_path + 'photo_tags.csv')
tags = pd.read_csv(data_path + 'tags.csv')
users = pd.read_csv(data_path + 'users.csv')

def normalize_columns(df):
    df = df.copy()
    df.columns = df.columns.str.strip().str.lower().str.replace(r'\s+', '_', regex=True)
    return df

photos = normalize_columns(photos)
comments = normalize_columns(comments)
likes = normalize_columns(likes)
follows = normalize_columns(follows)
photo_tags = normalize_columns(photo_tags)
tags = normalize_columns(tags)
users = normalize_columns(users)
print("All files are loaded successfully!!")

All files are loaded successfully!!

In [52]:
print("Photos shape: ", photos.shape)
print("Comments shape: ", comments.shape)
print("Likes shape: ", likes.shape)
print("Follows shape: ", follows.shape)
print("Photo Tags shape: ", photo_tags.shape)
print("Tags shape: ", tags.shape)
print("Users shape: ", users.shape)

Photos shape:  (257, 6)
Comments shape:  (7488, 8)
Likes shape:  (8782, 5)
Follows shape:  (7623, 5)
Photo Tags shape:  (501, 3)
Tags shape:  (21, 4)
Users shape:  (100, 6)

In [53]:
tables = {
    'photos': photos,
    'comments': comments,
    'likes': likes,
    'follows': follows,
    'photo_tags': photo_tags,
    'tags': tags,
    'users': users
}
# for name, df in tables.items():
#     print(f"\n{name.upper()}--> shape: {df.shape}")
#     print(df.columns.tolist())
#     print(df.head(2))

print("📊 INSTAGRAM DATASET SUMMARY\n" + "="*60)

for name, df in tables.items():
    print(f"\n🔹 {name.upper()} TABLE")
    print("-" * 50)
    print(f"Shape (Rows x Columns) : {df.shape[0]:,} rows × {df.shape[1]} columns")
    print(f"Columns ({len(df.columns)}):")
    
    # Print columns neatly
    for i, col in enumerate(df.columns, 1):
        print(f"   {i:2d}. {col}")
    
    print("\nFirst 2 Rows:")
    display(df.head(5))   # This shows nice formatted table
    print("-" * 60)

📊 INSTAGRAM DATASET SUMMARY
============================================================

🔹 PHOTOS TABLE
--------------------------------------------------
Shape (Rows x Columns) : 257 rows × 6 columns
Columns (6):
    1. id
    2. image_link
    3. user_id
    4. created_dat
    5. insta_filter_used
    6. photo_type

First 2 Rows:

,id,image_link,user_id,created_dat,insta_filter_used,photo_type
0,1,http://elijah.biz,1,13-04-2023 08:04,yes,photo
1,2,https://shanon.org,1,13-04-2023 08:04,no,photo
2,3,http://vicky.biz,1,13-04-2023 08:04,no,photo
3,4,http://oleta.net,1,13-04-2023 08:04,no,photo
4,5,https://jennings.biz,1,13-04-2023 08:04,yes,photo

------------------------------------------------------------

🔹 COMMENTS TABLE
--------------------------------------------------
Shape (Rows x Columns) : 7,488 rows × 8 columns
Columns (8):
    1. id
    2. comment
    3. user_id
    4. photo_id
    5. created_timestamp
    6. posted_date
    7. emoji_used
    8. hashtags_used_count

First 2 Rows:

,id,comment,user_id,photo_id,created_timestamp,posted_date,emoji_used,hashtags_used_count
0,1,unde at dolorem,2,1,13-04-2023 08:04,April 14,yes,1
1,2,quae ea ducimus,3,1,13-04-2023 08:04,April 14,no,2
2,3,alias a voluptatum,5,1,13-04-2023 08:04,April 14,no,4
3,4,facere suscipit sunt,14,1,13-04-2023 08:04,April 14,yes,2
4,5,totam eligendi quaerat,17,1,13-04-2023 08:04,April 14,yes,1

------------------------------------------------------------

🔹 LIKES TABLE
--------------------------------------------------
Shape (Rows x Columns) : 8,782 rows × 5 columns
Columns (5):
    1. user
    2. photo
    3. created_time
    4. following_or_not
    5. like_type

First 2 Rows:

   user  photo      created_time following_or_not    like_type
0     2      1  13-04-2023 08:04              yes  heart emoji
1     2      4  13-04-2023 08:04               no    thumbs up
2     2      8  13-04-2023 08:04              yes     laughing
3     2      9  13-04-2023 08:04               no         fire
4     2     10  13-04-2023 08:04              yes         clap

------------------------------------------------------------

🔹 FOLLOWS TABLE
--------------------------------------------------
Shape (Rows x Columns) : 7,623 rows × 5 columns
Columns (5):
    1. follower
    2. followee
    3. created_time
    4. is_follower_active
    5. followee_acc_status

First 2 Rows:

,follower,followee,created_time,is_follower_active,followee_acc_status
0,2,1,13-04-2023 08:04,1,Private
1,2,3,13-04-2023 08:04,0,private
2,2,4,13-04-2023 08:04,0,public
3,2,5,13-04-2023 08:04,0,private
4,2,6,13-04-2023 08:04,1,private

------------------------------------------------------------

🔹 PHOTO_TAGS TABLE
--------------------------------------------------
Shape (Rows x Columns) : 501 rows × 3 columns
Columns (3):
    1. photo
    2. tag_id
    3. user_id

First 2 Rows:

   photo  tag_id  user_id
0      1      13        1
1      1      17        1
2      1      18        2
3      1      19        2
4      1      21        3

------------------------------------------------------------

🔹 TAGS TABLE
--------------------------------------------------
Shape (Rows x Columns) : 21 rows × 4 columns
Columns (4):
    1. id
    2. tag_text
    3. created_time
    4. location

First 2 Rows:

   id     tag_text      created_time       location
0   1       sunset  13-04-2023 08:04        florida
1   2  photography  13-04-2023 08:04  washington DC
2   3      sunrise  13-04-2023 08:04       new york
3   4    landscape  13-04-2023 08:04         london
4   5         food  13-04-2023 08:04         brazil

------------------------------------------------------------

🔹 USERS TABLE
--------------------------------------------------
Shape (Rows x Columns) : 100 rows × 6 columns
Columns (6):
    1. id
    2. name
    3. created_time
    4. private/public
    5. post_count
    6. verified_status

First 2 Rows:

,id,name,created_time,private/public,post_count,verified_status
0,1,Kenton_Kirlin,16-02-2017 18:22,yes,11,no
1,2,Andre_Purdy85,02-04-2017 17:11,no,7,no
2,3,Harley_Lind18,21-02-2017 11:12,no,2,no
3,4,Arely_Bogan63,13-08-2016 01:28,yes,1,no
4,5,Aniya_Hackett,07-12-2016 01:04,yes,3,no

------------------------------------------------------------

In [54]:
# Build a reusable master table for analysis
# The normalized CSV keys are: id, user_id, photo, tag_id, follower, followee
master_df = photos.copy()

# 1) Add user profile details to each post
if 'user_id' in master_df.columns and 'id' in users.columns:
    master_df = master_df.merge(users, left_on='user_id', right_on='id', how='left', suffixes=('', '_user'))
    master_df = master_df.drop(columns=['id_user'], errors='ignore')

# 2) Aggregate hashtags per post
if {'photo', 'tag_id'}.issubset(photo_tags.columns) and {'id', 'tag_text'}.issubset(tags.columns):
    tags_info = photo_tags.merge(tags[['id', 'tag_text']], left_on='tag_id', right_on='id', how='left')
    hashtag_stats = tags_info.groupby('photo').agg(
        hashtag_count=('tag_text', 'count'),
        hashtags=('tag_text', lambda x: ', '.join(sorted(set(x.dropna()))))
    ).reset_index()
    hashtag_stats = hashtag_stats.rename(columns={'photo': 'id'})
    master_df = master_df.merge(hashtag_stats, on='id', how='left')

# 3) Add likes and comments counts
if 'photo' in likes.columns:
    likes_count = likes.groupby('photo').size().reset_index(name='total_likes')
    likes_count = likes_count.rename(columns={'photo': 'id'})
    master_df = master_df.merge(likes_count, on='id', how='left')

if 'photo_id' in comments.columns:
    comments_count = comments.groupby('photo_id').size().reset_index(name='total_comments')
    comments_count = comments_count.rename(columns={'photo_id': 'id'})
    master_df = master_df.merge(comments_count, on='id', how='left')

# 4) Add follower/following metrics from follows for user-level analysis
if {'follower', 'followee'}.issubset(follows.columns):
    followers_received = follows.groupby('followee').size().reset_index(name='followers_received')
    following_count = follows.groupby('follower').size().reset_index(name='following_count')
    master_df = master_df.merge(followers_received, left_on='user_id', right_on='followee', how='left')
    master_df = master_df.merge(following_count, left_on='user_id', right_on='follower', how='left')
    master_df = master_df.drop(columns=['followee', 'follower'], errors='ignore')

# Safe defaults for numeric columns
for col_name in ['hashtag_count', 'total_likes', 'total_comments', 'followers_received', 'following_count']:
    if col_name not in master_df.columns:
        master_df[col_name] = 0
    master_df[col_name] = master_df[col_name].fillna(0).astype(int)

# 5) Create analysis-ready metrics
master_df['total_engagement'] = master_df['total_likes'] + master_df['total_comments']
master_df['engagement_per_follower'] = master_df['total_engagement'] / master_df['followers_received'].replace(0, np.nan)

print('Master table created successfully')
print('Shape:', master_df.shape)
display(master_df.head(257))

Master table created successfully
Shape: (257, 19)

,id,image_link,user_id,created_dat,insta_filter_used,photo_type,name,created_time,private/public,post_count,verified_status,hashtag_count,hashtags,total_likes,total_comments,followers_received,following_count,total_engagement,engagement_per_follower
0,1,http://elijah.biz,1,13-04-2023 08:04,yes,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,5,"concert, drunk, fun, party, smile",25,25,77,0,50,0.649351
1,2,https://shanon.org,1,13-04-2023 08:04,no,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,4,"beach, landscape, photography, sunrise",36,31,77,0,67,0.870130
2,3,http://vicky.biz,1,13-04-2023 08:04,no,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,1,beauty,38,27,77,0,65,0.844156
3,4,http://oleta.net,1,13-04-2023 08:04,no,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,4,"fun, happy, lol, smile",38,32,77,0,70,0.909091
4,5,https://jennings.biz,1,13-04-2023 08:04,yes,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,4,"fashion, hair, party, style",31,27,77,0,58,0.753247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,http://ryleigh.info,99,13-04-2023 08:04,yes,photo,Alek_Watsica,10-12-2016 07:43,no,232,no,1,delicious,32,26,76,99,58,0.763158
253,254,https://darien.name,99,13-04-2023 08:04,no,carousel,Alek_Watsica,10-12-2016 07:43,no,232,no,4,"beach, landscape, photography, sunrise",31,26,76,99,57,0.750000
254,255,https://xzavier.org,99,13-04-2023 08:04,no,video,Alek_Watsica,10-12-2016 07:43,no,232,no,0,NaN,33,29,76,99,62,0.815789
255,256,https://kaela.name,100,13-04-2023 08:04,no,photo,Javonte83,27-03-2017 22:06,yes,32,yes,0,NaN,41,29,76,99,70,0.921053
256,257,http://dedrick.info,100,13-04-2023 08:04,yes,photo,Javonte83,27-03-2017 22:06,yes,32,yes,3,"concert, drunk, fun",36,24,76,99,60,0.789474

In [55]:
from pathlib import Path

# Export the analysis-ready master table to CSV
output_dir = Path('../data/exports')
output_dir.mkdir(parents=True, exist_ok=True)

master_csv_path = output_dir / 'master_df.csv'
master_df.to_csv(master_csv_path, index=False)

print(f'Master dataframe saved to: {master_csv_path.resolve()}')
print(f'Rows: {master_df.shape[0]}, Columns: {master_df.shape[1]}')

## Optional source tables too if you want them as separate CSVs  ##
# =======================================================================
# photos.to_csv(output_dir / 'photos_clean.csv', index=False)
# comments.to_csv(output_dir / 'comments_clean.csv', index=False)
# likes.to_csv(output_dir / 'likes_clean.csv', index=False)
# follows.to_csv(output_dir / 'follows_clean.csv', index=False)
# photo_tags.to_csv(output_dir / 'photo_tags_clean.csv', index=False)
# tags.to_csv(output_dir / 'tags_clean.csv', index=False)
# users.to_csv(output_dir / 'users_clean.csv', index=False)
# ===========================================================================


master_df.to_csv(output_dir / 'master_df.csv', index=False)
print('Also saved cleaned source tables into the same exports folder.')

Master dataframe saved to: C:\Users\lenovo\OneDrive\Documents\INSTAGRAM data analysis\data\exports\master_df.csv
Rows: 257, Columns: 19
Also saved cleaned source tables into the same exports folder.

In [47]:
master_df.head()

,id,image_link,user_id,created_dat,insta_filter_used,photo_type,name,created_time,private/public,post_count,verified_status,hashtag_count,hashtags,total_likes,total_comments,followers_received,following_count,total_engagement,engagement_per_follower
0,1,http://elijah.biz,1,13-04-2023 08:04,yes,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,5,"concert, drunk, fun, party, smile",25,25,77,0,50,0.649351
1,2,https://shanon.org,1,13-04-2023 08:04,no,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,4,"beach, landscape, photography, sunrise",36,31,77,0,67,0.870130
2,3,http://vicky.biz,1,13-04-2023 08:04,no,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,1,beauty,38,27,77,0,65,0.844156
3,4,http://oleta.net,1,13-04-2023 08:04,no,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,4,"fun, happy, lol, smile",38,32,77,0,70,0.909091
4,5,https://jennings.biz,1,13-04-2023 08:04,yes,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,4,"fashion, hair, party, style",31,27,77,0,58,0.753247

In [56]:
# ===================== PROBLEM 2: CONTENT TYPE & HASHTAG ANALYSIS =====================

# 1. Engagement by Number of Hashtags
hashtag_perf = master_df.groupby('hashtag_count').agg({
    'total_engagement': ['mean', 'median', 'count'],
    'engagement_per_follower': 'mean'
}).round(2)

hashtag_perf.columns = ['Avg_Engagement', 'Median_Engagement', 'Post_Count', 'Avg_Eng_Rate']
print("Engagement by Number of Hashtags:")
display(hashtag_perf)

# 2. Top Performing Hashtags
if 'hashtags' in master_df.columns:
    all_tags = []
    for row in master_df['hashtags'].dropna():
        all_tags.extend([tag.strip() for tag in row.split(',') if tag.strip()])
    
    from collections import Counter
    tag_count = Counter(all_tags)
    
    top_tags = pd.DataFrame(tag_count.most_common(15), columns=['Hashtag', 'Usage_Count'])
    print("\n🔥 Top 15 Most Used Hashtags:")
    display(top_tags)

Engagement by Number of Hashtags:

               Avg_Engagement  Median_Engagement  Post_Count  Avg_Eng_Rate
hashtag_count
0                       63.04               63.0          67          0.83
1                       63.21               62.0          47          0.83
2                       63.02               62.0          43          0.83
3                       63.54               63.0          50          0.83
4                       63.62               64.0          32          0.83
5                       64.00               63.0          18          0.84

🔥 Top 15 Most Used Hashtags:

      Hashtag  Usage_Count
0       smile           59
1       beach           42
2       party           39
3         fun           38
4     concert           24
5         lol           24
6        food           24
7        hair           23
8       happy           22
9      beauty           20
10     dreamy           20
11      drunk           19
12    fashion           19
13     sunset           19
14  landscape           17